# verl/trainer/ppo/erl_reflection_prompt.py
"""
Builds the reflection prompt for ERL.

The reflection is generated by the SAME model (πθ) conditioned on:
  (x, y1, f1, r1, m)
where m is the cross-episode memory of successful reflections.
"""

from __future__ import annotations

_REFLECTION_SYSTEM = """\
你是一名专业的反思分析助手。你的任务是分析一次股票代码识别任务的尝试结果，\
找出其中的不足，并给出明确的改进建议，帮助下一次尝试做得更好。
重要约束：
- 不要在反思中给出具体的股票代码答案
- 只分析分析方法和工具使用策略，不要泄露正确答案
- 下一次尝试必须独立通过工具验证得出结论"""

_REFLECTION_TEMPLATE = """\
## 任务
{task_description}

## 第一次尝试的过程
{first_attempt}

## 环境反馈
{feedback}

## 得分
{reward:.3f}（满分1.0）

{memory_section}\
## 请进行反思

请简要分析：
1. 第一次尝试中哪些关键线索被忽略或误判了？
2. 使用了哪些工具？哪些工具调用是有效的，哪些是冗余的？
3. 下一次应该采取什么不同的策略？

请给出具体、可执行的改进建议。"""

_MEMORY_SECTION_TEMPLATE = """\
## 历史成功经验（供参考）
{memories}

"""


def build_reflection_prompt(
    task_description: str,
    first_attempt: str,
    feedback: str,
    reward: float,
    memories: list[str],
) -> str:
    """
    Construct the user-turn content for reflection generation.

    Args:
        task_description: The original task / question shown to the model.
        first_attempt:    The full first-attempt trajectory text.
        feedback:         Environment feedback text (e.g., from calc_stock_reward).
        reward:           Scalar reward from the first attempt.
        memories:         List of previously successful reflections from memory.
    """
    if memories:
        mem_text = "\n".join(f"- {m}" for m in memories)
        memory_section = _MEMORY_SECTION_TEMPLATE.format(memories=mem_text)
    else:
        memory_section = ""

    return _REFLECTION_TEMPLATE.format(
        task_description=task_description,
        first_attempt=first_attempt,
        feedback=feedback,
        reward=reward,
        memory_section=memory_section,
    )