#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export JOB_NAME=${JOB_NAME:-8_state_agreement_grpo}
export POLICY_LOSS_MODE=${POLICY_LOSS_MODE:-state_agreement_grpo}
export STATE_PREDICTIVE_OBJECTIVE=${STATE_PREDICTIVE_OBJECTIVE:-agreement}
export STATE_PREDICTIVE_AGREEMENT_SCORE_MODE=${STATE_PREDICTIVE_AGREEMENT_SCORE_MODE:-raw}
export STATE_PREDICTIVE_SEGMENT_BACKEND=${STATE_PREDICTIVE_SEGMENT_BACKEND:-torch}
export STATE_PREDICTIVE_PRECOMPUTE_STATE_INDEX=${STATE_PREDICTIVE_PRECOMPUTE_STATE_INDEX:-True}
export STATE_PREDICTIVE_USE_UPDATE_SKETCH=${STATE_PREDICTIVE_USE_UPDATE_SKETCH:-True}
export STATE_PREDICTIVE_NORMALIZE_FEATURES=${STATE_PREDICTIVE_NORMALIZE_FEATURES:-True}
export CALCULATE_UPDATE_SKETCH=${CALCULATE_UPDATE_SKETCH:-$STATE_PREDICTIVE_USE_UPDATE_SKETCH}

exec "$SCRIPT_DIR/demo_state_predictive_grpo.sh" "$@"
