#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export JOB_NAME="${JOB_NAME:-multidomain_sp_md_bos_grpo}"
export ADV_ESTIMATOR=shared_private_multi_domain_bos_grpo
export POLICY_LOSS_MODE="${POLICY_LOSS_MODE:-vanilla}"

# Use the Megatron CountSketch proxy S(e_y - pi) for shared/private subspaces.
export CALCULATE_UPDATE_SKETCH="${CALCULATE_UPDATE_SKETCH:-True}"
export UPDATE_SKETCH_DIM="${UPDATE_SKETCH_DIM:-64}"
export UPDATE_SKETCH_SEED="${UPDATE_SKETCH_SEED:-17}"

export SP_MD_BOS_GRPO_SHARED_K="${SP_MD_BOS_GRPO_SHARED_K:-4}"
export SP_MD_BOS_GRPO_PRIVATE_K="${SP_MD_BOS_GRPO_PRIVATE_K:-2}"
export SP_MD_BOS_GRPO_DOMAIN_LAMBDA="${SP_MD_BOS_GRPO_DOMAIN_LAMBDA:-1.0}"
export SP_MD_BOS_GRPO_SHARED_NOISE_LAMBDA="${SP_MD_BOS_GRPO_SHARED_NOISE_LAMBDA:-1.0}"
export SP_MD_BOS_GRPO_PRIVATE_NOISE_LAMBDA="${SP_MD_BOS_GRPO_PRIVATE_NOISE_LAMBDA:-1.0}"
export SP_MD_BOS_GRPO_WEIGHT_FLOOR="${SP_MD_BOS_GRPO_WEIGHT_FLOOR:-0.3}"
export SP_MD_BOS_GRPO_WEIGHT_POWER="${SP_MD_BOS_GRPO_WEIGHT_POWER:-1.0}"
export SP_MD_BOS_GRPO_MIX_WITH_VANILLA="${SP_MD_BOS_GRPO_MIX_WITH_VANILLA:-0.3}"
export SP_MD_BOS_GRPO_POSITIVE_EIGS_ONLY="${SP_MD_BOS_GRPO_POSITIVE_EIGS_ONLY:-True}"
export SP_MD_BOS_GRPO_FALLBACK_TO_VANILLA="${SP_MD_BOS_GRPO_FALLBACK_TO_VANILLA:-True}"
export SP_MD_BOS_GRPO_INCLUDE_FEATURE_STD="${SP_MD_BOS_GRPO_INCLUDE_FEATURE_STD:-False}"
export SP_MD_BOS_GRPO_NORMALIZE_FEATURES="${SP_MD_BOS_GRPO_NORMALIZE_FEATURES:-True}"
export SP_MD_BOS_GRPO_EPS="${SP_MD_BOS_GRPO_EPS:-1e-6}"
export SP_MD_BOS_GRPO_DOMAIN_KEY="${SP_MD_BOS_GRPO_DOMAIN_KEY:-domain}"
export SP_MD_BOS_GRPO_MIN_DOMAIN_COUNT="${SP_MD_BOS_GRPO_MIN_DOMAIN_COUNT:-2}"
export EXTRA_SP_MD_BOS_GRPO_OVERRIDES=1

"$SCRIPT_DIR/reflect_demo_multidomain.sh" "$@"
