#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export JOB_NAME="${JOB_NAME:-multidomain_md_bos_grpo}"
export ADV_ESTIMATOR=multi_domain_bos_grpo
export POLICY_LOSS_MODE="${POLICY_LOSS_MODE:-vanilla}"

# Use the Megatron CountSketch proxy S(e_y - pi) for MD-BOS subspace estimation.
export CALCULATE_UPDATE_SKETCH="${CALCULATE_UPDATE_SKETCH:-True}"
export UPDATE_SKETCH_DIM="${UPDATE_SKETCH_DIM:-64}"
export UPDATE_SKETCH_SEED="${UPDATE_SKETCH_SEED:-17}"

export MD_BOS_GRPO_K="${MD_BOS_GRPO_K:-4}"
export MD_BOS_GRPO_DOMAIN_LAMBDA="${MD_BOS_GRPO_DOMAIN_LAMBDA:-1.0}"
export MD_BOS_GRPO_NOISE_LAMBDA="${MD_BOS_GRPO_NOISE_LAMBDA:-1.0}"
export MD_BOS_GRPO_WEIGHT_FLOOR="${MD_BOS_GRPO_WEIGHT_FLOOR:-0.1}"
export MD_BOS_GRPO_WEIGHT_POWER="${MD_BOS_GRPO_WEIGHT_POWER:-1.0}"
export MD_BOS_GRPO_MIX_WITH_VANILLA="${MD_BOS_GRPO_MIX_WITH_VANILLA:-0.0}"
export MD_BOS_GRPO_POSITIVE_EIGS_ONLY="${MD_BOS_GRPO_POSITIVE_EIGS_ONLY:-True}"
export MD_BOS_GRPO_FALLBACK_TO_VANILLA="${MD_BOS_GRPO_FALLBACK_TO_VANILLA:-True}"
export MD_BOS_GRPO_INCLUDE_FEATURE_STD="${MD_BOS_GRPO_INCLUDE_FEATURE_STD:-False}"
export MD_BOS_GRPO_NORMALIZE_FEATURES="${MD_BOS_GRPO_NORMALIZE_FEATURES:-True}"
export MD_BOS_GRPO_EPS="${MD_BOS_GRPO_EPS:-1e-6}"
export MD_BOS_GRPO_DOMAIN_KEY="${MD_BOS_GRPO_DOMAIN_KEY:-domain}"
export MD_BOS_GRPO_MIN_DOMAIN_COUNT="${MD_BOS_GRPO_MIN_DOMAIN_COUNT:-2}"
export EXTRA_MD_BOS_GRPO_OVERRIDES=1

"$SCRIPT_DIR/reflect_demo_multidomain.sh" "$@"
