"""Local HDL judging utilities used by the HDL RL agent loop.

The judge intentionally uses the isolated toolchain generated by
``hdl_env/rebuild_hdl_env.sh``.  It supports two submission modes:

* SystemVerilog/Verilog: extract RTL and run Slang, Verilator, simulation, and
  Yosys according to task metadata.
* Chisel/Scala: compile/elaborate with Maven/Chisel first, then judge the
  emitted SystemVerilog through the same RTL path.
"""

from __future__ import annotations

import json
import os
import re
import shlex
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parents[2]
_DEFAULT_ENV_SH = _REPO_ROOT / "hdl_env" / "env.sh"
_DEFAULT_WORK_BASE = _REPO_ROOT / "hdl_env" / "tmp" / "agent_judge"

_FENCE_RE = re.compile(r"```([A-Za-z0-9_+.#-]*)\s*\n(.*?)```", re.DOTALL)
_HDL_TAG_RE = re.compile(r"<(?:HDL|RTL|SYSTEMVERILOG|VERILOG|CHISEL|SCALA)>(.*?)</(?:HDL|RTL|SYSTEMVERILOG|VERILOG|CHISEL|SCALA)>", re.DOTALL | re.IGNORECASE)
_TOOL_RESPONSE_RE = re.compile(r"<tool_response>.*?</tool_response>", re.DOTALL | re.IGNORECASE)
_THINK_RE = re.compile(r"<think>.*?</think>", re.DOTALL | re.IGNORECASE)


@dataclass
class CommandResult:
    name: str
    cmd: list[str]
    returncode: int
    stdout: str
    stderr: str
    timed_out: bool = False

    @property
    def ok(self) -> bool:
        return self.returncode == 0 and not self.timed_out

    @property
    def output(self) -> str:
        text = "\n".join(part for part in (self.stdout, self.stderr) if part).strip()
        return text or "<no output>"


def _truncate(text: str, limit: int = 6000) -> str:
    text = text or ""
    if len(text) <= limit:
        return text
    keep = max(0, (limit - 80) // 2)
    return text[:keep] + "\n...(truncated)...\n" + text[-keep:]


def _as_bool(value: Any, default: bool = False) -> bool:
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.strip().lower() in {"1", "true", "yes", "y", "on"}
    return bool(value)


def _json_loads_maybe(value: Any) -> Any:
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return value
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            return value
    return value


def _load_task(ground_truth: Any, extra_info: dict[str, Any] | None = None) -> dict[str, Any]:
    extra_info = extra_info or {}
    task = _json_loads_maybe(ground_truth)
    if not isinstance(task, dict):
        task = _json_loads_maybe(extra_info.get("hdl_task"))
    if not isinstance(task, dict):
        meta = _json_loads_maybe(extra_info.get("meta_json"))
        if isinstance(meta, dict):
            task = _json_loads_maybe(meta.get("hdl_task"))
    if not isinstance(task, dict):
        raise ValueError("HDL reward ground_truth must be a task JSON object")
    return task


@lru_cache(maxsize=16)
def _load_hidden_tests(path: str) -> dict[str, dict[str, Any]]:
    hidden_path = Path(os.path.expanduser(path)).resolve()
    if not hidden_path.is_file():
        return {}

    text = hidden_path.read_text(encoding="utf-8").strip()
    if not text:
        return {}

    by_task_id: dict[str, dict[str, Any]] = {}
    if hidden_path.suffix != ".jsonl":
        try:
            payload = json.loads(text)
        except json.JSONDecodeError:
            payload = None
        if isinstance(payload, dict):
            for key, value in payload.items():
                if isinstance(value, dict):
                    row = dict(value)
                    row.setdefault("task_id", key)
                    by_task_id[str(row["task_id"])] = row
            return by_task_id

    for line in text.splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        if isinstance(row, dict) and row.get("task_id"):
            by_task_id[str(row["task_id"])] = row
    return by_task_id


def _merge_hidden_reward_task(task: dict[str, Any], extra_info: dict[str, Any] | None) -> dict[str, Any]:
    extra_info = extra_info or {}
    merged = dict(task)

    inline_hidden = _json_loads_maybe(extra_info.get("hdl_hidden_task"))
    if isinstance(inline_hidden, dict):
        merged.update(inline_hidden)

    hidden_tests_path = extra_info.get("hdl_hidden_tests_path")
    task_id = str(merged.get("task_id") or "")
    if hidden_tests_path and task_id:
        hidden_task = _load_hidden_tests(str(hidden_tests_path)).get(task_id)
        if isinstance(hidden_task, dict):
            merged.update(hidden_task)

    return merged


def task_from_tool_parameters(parameters: dict[str, Any], default_task: dict[str, Any] | None = None) -> dict[str, Any]:
    """Build a judge task from model tool parameters and optional dataset task."""

    task = dict(default_task or {})
    task_payload = _json_loads_maybe(parameters.get("task"))
    if isinstance(task_payload, dict):
        task.update(task_payload)

    for key in (
        "language",
        "top_module",
        "top",
        "testbench_cpp",
        "yosys_script",
        "env_sh",
        "timeout",
        "feedback_max_chars",
    ):
        if parameters.get(key) not in (None, ""):
            task[key] = parameters[key]

    for key in ("synthesis", "slang", "verilator_lint", "stop_on_frontend_error"):
        if parameters.get(key) is not None:
            task[key] = _as_bool(parameters[key])

    task.setdefault("language", "systemverilog")
    task.setdefault("top_module", task.get("top") or "Top")
    return task


def _clean_solution_text(solution_str: str) -> str:
    text = _TOOL_RESPONSE_RE.sub("", solution_str or "")
    text = _THINK_RE.sub("", text)
    return text.strip()


def _ensure_trailing_newline(text: str) -> str:
    return text if text.endswith("\n") else text + "\n"


def extract_hdl_code(solution_str: str, language: str | None = None) -> str:
    """Extract candidate HDL/Scala code from a model completion.

    Prefer explicit fenced code blocks and ``<HDL>``-style tags.  If neither is
    present, fall back to a raw module/class region before returning the whole
    cleaned response.
    """

    text = _clean_solution_text(solution_str)
    language = (language or "systemverilog").lower()
    preferred_labels = (
        {"scala", "chisel"}
        if language in {"chisel", "scala"}
        else {"systemverilog", "sv", "verilog", "v", "rtl"}
    )

    fences = [(label.lower(), body.strip()) for label, body in _FENCE_RE.findall(text)]
    for label, body in fences:
        if label in preferred_labels and body:
            return body
    for label, body in fences:
        if body:
            return body

    tag_match = _HDL_TAG_RE.search(text)
    if tag_match:
        return tag_match.group(1).strip()

    if language in {"chisel", "scala"}:
        chisel_start = re.search(r"(?m)^\s*(?:import\s+chisel3|class\s+\w+\s*\(|object\s+\w+\s+extends)", text)
        if chisel_start:
            return text[chisel_start.start() :].strip()
    else:
        modules = list(re.finditer(r"\bmodule\s+\w+\b.*?\bendmodule\b", text, re.DOTALL))
        if modules:
            return "\n\n".join(match.group(0).strip() for match in modules)

    return text


def _env_sh_path(task: dict[str, Any], explicit_env_sh: str | os.PathLike[str] | None = None) -> Path:
    value = explicit_env_sh or task.get("env_sh") or os.environ.get("HDL_ENV_SH") or str(_DEFAULT_ENV_SH)
    return Path(os.path.expanduser(str(value))).resolve()


def _run_cmd(
    name: str,
    args: list[str],
    *,
    cwd: Path,
    env_sh: Path,
    timeout: int,
) -> CommandResult:
    if not env_sh.is_file():
        return CommandResult(
            name=name,
            cmd=args,
            returncode=127,
            stdout="",
            stderr=f"Missing HDL environment file: {env_sh}. Run bash hdl_env/rebuild_hdl_env.sh first.",
        )

    command = "source " + shlex.quote(str(env_sh)) + " && " + " ".join(shlex.quote(str(arg)) for arg in args)
    try:
        proc = subprocess.run(
            ["/bin/bash", "-lc", command],
            cwd=str(cwd),
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=timeout,
            env=os.environ.copy(),
        )
        return CommandResult(name=name, cmd=args, returncode=proc.returncode, stdout=proc.stdout, stderr=proc.stderr)
    except subprocess.TimeoutExpired as exc:
        stdout = exc.stdout if isinstance(exc.stdout, str) else (exc.stdout or b"").decode(errors="replace")
        stderr = exc.stderr if isinstance(exc.stderr, str) else (exc.stderr or b"").decode(errors="replace")
        return CommandResult(
            name=name,
            cmd=args,
            returncode=124,
            stdout=stdout,
            stderr=stderr + f"\nTimed out after {timeout}s",
            timed_out=True,
        )


def _write_support_files(task: dict[str, Any], work_dir: Path) -> list[Path]:
    files: list[Path] = []
    for index, item in enumerate(task.get("files") or []):
        if not isinstance(item, dict):
            continue
        rel_path = str(item.get("path") or f"support_{index}.sv")
        safe_path = Path(rel_path)
        if safe_path.is_absolute() or ".." in safe_path.parts:
            raise ValueError(f"Unsafe HDL support file path: {rel_path}")
        path = work_dir / safe_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(str(item.get("content") or ""), encoding="utf-8")
        files.append(path)
    return files


def _maven_pom(chisel_version: str = "7.2.0", scala_version: str = "2.13.17") -> str:
    return f"""<project xmlns=\"http://maven.apache.org/POM/4.0.0\"
         xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
         xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd\">
  <modelVersion>4.0.0</modelVersion>
  <groupId>local.hdl</groupId>
  <artifactId>hdl-agent-candidate</artifactId>
  <version>0.1.0</version>
  <properties>
    <scala.version>{scala_version}</scala.version>
    <chisel.version>{chisel_version}</chisel.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.chipsalliance</groupId>
      <artifactId>chisel_2.13</artifactId>
      <version>${{chisel.version}}</version>
    </dependency>
  </dependencies>
  <build>
    <sourceDirectory>src/main/scala</sourceDirectory>
    <plugins>
      <plugin>
        <groupId>net.alchim31.maven</groupId>
        <artifactId>scala-maven-plugin</artifactId>
        <version>4.9.10</version>
        <configuration>
          <scalaVersion>${{scala.version}}</scalaVersion>
          <compilerPlugins>
            <compilerPlugin>
              <groupId>org.chipsalliance</groupId>
              <artifactId>chisel-plugin_2.13.17</artifactId>
              <version>${{chisel.version}}</version>
            </compilerPlugin>
          </compilerPlugins>
        </configuration>
        <executions>
          <execution>
            <goals><goal>compile</goal></goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>3.5.0</version>
        <configuration>
          <mainClass>Elaborate</mainClass>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
"""


def _elaborate_chisel(
    code: str,
    task: dict[str, Any],
    *,
    work_dir: Path,
    env_sh: Path,
    timeout: int,
) -> tuple[Path | None, CommandResult]:
    project = work_dir / "chisel"
    src_dir = project / "src" / "main" / "scala"
    src_dir.mkdir(parents=True, exist_ok=True)
    (project / "pom.xml").write_text(
        _maven_pom(
            str(task.get("chisel_version") or "7.2.0"),
            str(task.get("scala_version") or "2.13.17"),
        ),
        encoding="utf-8",
    )
    (src_dir / "Submission.scala").write_text(code, encoding="utf-8")

    result = _run_cmd(
        "chisel_elaborate",
        ["mvn", "-q", "compile", "exec:java"],
        cwd=project,
        env_sh=env_sh,
        timeout=timeout,
    )
    if not result.ok:
        return None, result

    full_sv = work_dir / "candidate.full.sv"
    full_sv.write_text(result.stdout, encoding="utf-8")
    sv_text = []
    for line in result.stdout.splitlines():
        if line.startswith("// ----- 8< ----- FILE "):
            break
        sv_text.append(line)
    sv_path = work_dir / "candidate.sv"
    sv_path.write_text("\n".join(sv_text).strip() + "\n", encoding="utf-8")
    return sv_path, result


def _score_weighted(checks: dict[str, bool], task: dict[str, Any]) -> float:
    language = str(task.get("language") or "systemverilog").lower()
    weights: dict[str, float] = {"extract": 0.05}
    if language in {"chisel", "scala"}:
        weights["chisel_elaborate"] = 0.15
    weights["slang"] = 0.15
    if task.get("verilator_lint", True):
        weights["verilator_lint"] = 0.10
    if task.get("testbench_cpp"):
        weights["verilator_sim"] = 0.40
    if task.get("synthesis", True):
        weights["yosys_synth"] = max(0.0, 1.0 - sum(weights.values()))

    score = sum(weight for name, weight in weights.items() if checks.get(name))
    return max(-0.1, min(1.0, score))


def _phase_score(checks: dict[str, Any], task: dict[str, Any], phase: str) -> float:
    phase = str(phase or "full").lower()
    if phase == "compile":
        required = ["extract", "slang", "verilator_lint"]
        if str(task.get("language") or "systemverilog").lower() in {"chisel", "scala"}:
            required.insert(1, "chisel_elaborate")
        passed = sum(1 for name in required if checks.get(name))
        return passed / len(required)
    if phase == "simulate":
        required = ["extract", "slang", "verilator_lint", "verilator_sim"]
        if str(task.get("language") or "systemverilog").lower() in {"chisel", "scala"}:
            required.insert(1, "chisel_elaborate")
        passed = sum(1 for name in required if checks.get(name))
        score = passed / len(required)
        if checks.get("verilator_sim_mode") == "auto_smoke":
            score = min(score, 0.75)
        return score
    if phase == "synthesize":
        required = ["extract", "slang", "verilator_lint", "yosys_synth"]
        if str(task.get("language") or "systemverilog").lower() in {"chisel", "scala"}:
            required.insert(1, "chisel_elaborate")
        passed = sum(1 for name in required if checks.get(name))
        return passed / len(required)
    return _score_weighted(checks, task)


def _status_line(name: str, ok: bool | None) -> str:
    if ok is None:
        state = "SKIP"
    else:
        state = "PASS" if ok else "FAIL"
    return f"- {name}: {state}"


def _sim_status_line(ok: bool | None, sim_mode: Any) -> str:
    if ok is None:
        return _status_line("Verilator simulation", None)
    state = "PASS" if ok else "FAIL"
    if sim_mode == "auto_smoke":
        return f"- Verilator simulation: {state} (auto-smoke only; no functional C++ testbench_cpp)"
    if sim_mode == "testbench_cpp":
        return f"- Verilator simulation: {state} (C++ testbench_cpp)"
    return f"- Verilator simulation: {state}"


def _verilator_class_name(top: str) -> str:
    return "V" + re.sub(r"[^A-Za-z0-9_]", "_", top)


def _smoke_testbench_cpp(top: str) -> str:
    class_name = _verilator_class_name(top)
    return f'''#include "{class_name}.h"
#include "verilated.h"

int main(int argc, char** argv) {{
    Verilated::commandArgs(argc, argv);
    {class_name} dut;
    dut.eval();
    return 0;
}}
'''


def _build_feedback(results: list[CommandResult], checks: dict[str, bool], score: float, limit: int) -> str:
    lines = ["HDL judge result:", f"score: {score:.3f}"]
    lines.extend(
        [
            _status_line("code extraction", checks.get("extract")),
            _status_line("Chisel elaboration", checks.get("chisel_elaborate")),
            _status_line("Slang parse/semantic", checks.get("slang")),
            _status_line("Verilator lint", checks.get("verilator_lint")),
            _sim_status_line(checks.get("verilator_sim"), checks.get("verilator_sim_mode")),
            _status_line("Yosys synthesis", checks.get("yosys_synth")),
        ]
    )
    if checks.get("verilator_sim_mode") == "auto_smoke":
        lines.append(
            "Simulation note: auto-smoke only proves that Verilator can build and run the design. "
            "It does not check functional correctness; provide testbench_cpp for a real simulation check."
        )
    first_failure = next((result for result in results if not result.ok), None)
    if first_failure is not None:
        lines.append(f"\nFirst failing step: {first_failure.name}")
        lines.append("Command: " + shlex.join(str(arg) for arg in first_failure.cmd))
        lines.append(_truncate(first_failure.output, max(500, limit - len("\n".join(lines)))))
    elif results:
        lines.append("\nAll requested judge steps passed.")
    return _truncate("\n".join(lines), limit)


def compute_hdl_score(
    data_source: str | None = None,
    solution_str: str | None = None,
    ground_truth: Any | None = None,
    extra_info: dict[str, Any] | None = None,
    *,
    work_dir: str | os.PathLike[str] | None = None,
    env_sh: str | os.PathLike[str] | None = None,
    keep_work: bool | None = None,
    timeout: int | None = None,
    feedback_max_chars: int | None = None,
    **kwargs: Any,
) -> dict[str, Any]:
    return compute_hdl_score_for_phase(
        data_source=data_source,
        solution_str=solution_str,
        ground_truth=ground_truth,
        extra_info=extra_info,
        phase="full",
        work_dir=work_dir,
        env_sh=env_sh,
        keep_work=keep_work,
        timeout=timeout,
        feedback_max_chars=feedback_max_chars,
        **kwargs,
    )


def compute_hdl_score_for_phase(
    data_source: str | None = None,
    solution_str: str | None = None,
    ground_truth: Any | None = None,
    extra_info: dict[str, Any] | None = None,
    *,
    phase: str = "full",
    work_dir: str | os.PathLike[str] | None = None,
    env_sh: str | os.PathLike[str] | None = None,
    keep_work: bool | None = None,
    timeout: int | None = None,
    feedback_max_chars: int | None = None,
    **kwargs: Any,
) -> dict[str, Any]:
    """Compute HDL reward from a model completion and task JSON.

    Args match VERL's custom reward function convention.  ``data_source`` is
    accepted for compatibility and ignored by the local judge.
    """

    del data_source, kwargs
    phase = str(phase or "full").lower()
    task = _load_task(ground_truth, extra_info)
    if phase == "full":
        task = _merge_hidden_reward_task(task, extra_info)
    if phase == "compile":
        task = {**task, "testbench_cpp": None, "synthesis": False}
    elif phase == "simulate":
        task = {**task, "synthesis": False}
    elif phase == "synthesize":
        task = {**task, "testbench_cpp": None, "synthesis": True}
    elif phase != "full":
        raise ValueError(f"Unknown HDL judge phase: {phase}")
    language = str(task.get("language") or "systemverilog").lower()
    env_sh = _env_sh_path(task, env_sh)
    timeout = int(timeout or task.get("timeout") or os.environ.get("HDL_AGENT_TIMEOUT", 30))
    feedback_max_chars = int(
        feedback_max_chars or task.get("feedback_max_chars") or os.environ.get("HDL_AGENT_FEEDBACK_MAX_CHARS", 6000)
    )
    keep_work = _as_bool(keep_work, _as_bool(os.environ.get("HDL_AGENT_KEEP_WORK"), False))

    base_dir = Path(work_dir) if work_dir else Path(os.environ.get("HDL_AGENT_WORK_DIR", str(_DEFAULT_WORK_BASE)))
    base_dir.mkdir(parents=True, exist_ok=True)
    run_dir = Path(tempfile.mkdtemp(prefix="case_", dir=str(base_dir)))

    results: list[CommandResult] = []
    checks: dict[str, bool] = {"extract": False}
    score = -0.1
    code = ""
    try:
        code = extract_hdl_code(solution_str or "", language)
        checks["extract"] = bool(code.strip())
        if not checks["extract"]:
            feedback = "HDL judge result:\nscore: -0.100\n- code extraction: FAIL\nNo HDL/Chisel code found."
            return {
                "score": -0.1,
                "acc": 0.0,
                "hdl_feedback": feedback,
                "hdl_extract_ok": 0.0,
                "hdl_work_dir": str(run_dir) if keep_work else "",
            }

        code = _ensure_trailing_newline(code)
        (run_dir / "candidate.original.txt").write_text(code, encoding="utf-8")
        support_files = _write_support_files(task, run_dir)

        if language in {"chisel", "scala"}:
            sv_path, elab = _elaborate_chisel(code, task, work_dir=run_dir, env_sh=env_sh, timeout=timeout)
            results.append(elab)
            checks["chisel_elaborate"] = elab.ok
            if not elab.ok or sv_path is None:
                failed_score = _phase_score(checks, task, phase)
                feedback = _build_feedback(results, checks, failed_score, feedback_max_chars)
                return _result_dict(checks, results, task, feedback, run_dir, keep_work, code, score=failed_score)
        else:
            sv_path = run_dir / "candidate.sv"
            sv_path.write_text(code, encoding="utf-8")
            checks["chisel_elaborate"] = None  # type: ignore[assignment]

        top = str(task.get("top_module") or task.get("top") or "Top")
        sv_files = [str(path.relative_to(run_dir)) for path in support_files + [sv_path]]

        if task.get("slang", True):
            slang = _run_cmd("slang", ["slang", *sv_files], cwd=run_dir, env_sh=env_sh, timeout=timeout)
            results.append(slang)
            checks["slang"] = slang.ok
            if not slang.ok and task.get("stop_on_frontend_error", True):
                failed_score = _phase_score(checks, task, phase)
                feedback = _build_feedback(results, checks, failed_score, feedback_max_chars)
                return _result_dict(checks, results, task, feedback, run_dir, keep_work, code, score=failed_score)

        if task.get("verilator_lint", True):
            lint_flags = [str(flag) for flag in task.get("verilator_lint_flags", ["-Wall", "-Wno-DECLFILENAME"])]
            if language in {"chisel", "scala"} and "-Wno-UNUSED" not in lint_flags:
                lint_flags.append("-Wno-UNUSED")
            lint = _run_cmd(
                "verilator_lint",
                ["verilator", "--lint-only", *lint_flags, "--top-module", top, *sv_files],
                cwd=run_dir,
                env_sh=env_sh,
                timeout=timeout,
            )
            results.append(lint)
            checks["verilator_lint"] = lint.ok
            if not lint.ok and task.get("stop_on_frontend_error", True):
                failed_score = _phase_score(checks, task, phase)
                feedback = _build_feedback(results, checks, failed_score, feedback_max_chars)
                return _result_dict(checks, results, task, feedback, run_dir, keep_work, code, score=failed_score)

        testbench_cpp = task.get("testbench_cpp")
        sim_mode = None
        if not testbench_cpp and phase == "simulate":
            testbench_cpp = _smoke_testbench_cpp(top)
            sim_mode = "auto_smoke"
        elif testbench_cpp:
            sim_mode = "testbench_cpp"

        if testbench_cpp:
            tb_path = run_dir / "tb.cpp"
            tb_path.write_text(str(testbench_cpp), encoding="utf-8")
            obj_dir = run_dir / "obj_dir"
            sim_flags = [str(flag) for flag in task.get("verilator_sim_flags", [])]
            compile_sim = _run_cmd(
                "verilator_sim_compile",
                [
                    "verilator",
                    "-cc",
                    "--exe",
                    *sim_flags,
                    "--top-module",
                    top,
                    "-Mdir",
                    str(obj_dir.relative_to(run_dir)),
                    *sv_files,
                    str(tb_path.relative_to(run_dir)),
                ],
                cwd=run_dir,
                env_sh=env_sh,
                timeout=timeout,
            )
            results.append(compile_sim)
            make_ok = False
            run_ok = False
            if compile_sim.ok:
                make = _run_cmd(
                    "verilator_sim_make",
                    ["make", "-C", str(obj_dir.relative_to(run_dir)), "-f", f"V{top}.mk"],
                    cwd=run_dir,
                    env_sh=env_sh,
                    timeout=timeout,
                )
                results.append(make)
                make_ok = make.ok
                if make.ok:
                    run_sim = _run_cmd(
                        "verilator_sim_run",
                        [str((obj_dir / f"V{top}").relative_to(run_dir))],
                        cwd=run_dir,
                        env_sh=env_sh,
                        timeout=timeout,
                    )
                    results.append(run_sim)
                    run_ok = run_sim.ok
            checks["verilator_sim"] = bool(compile_sim.ok and make_ok and run_ok)
            checks["verilator_sim_mode"] = sim_mode  # type: ignore[assignment]
        else:
            checks["verilator_sim"] = None  # type: ignore[assignment]
            checks["verilator_sim_mode"] = None  # type: ignore[assignment]

        if task.get("synthesis", True):
            if task.get("yosys_script"):
                yosys_script = str(task["yosys_script"])
            else:
                yosys_script = f"read_verilog -sv {' '.join(sv_files)}; synth -top {top}; stat"
            synth = _run_cmd("yosys_synth", ["yosys", "-q", "-p", yosys_script], cwd=run_dir, env_sh=env_sh, timeout=timeout)
            results.append(synth)
            checks["yosys_synth"] = synth.ok
        else:
            checks["yosys_synth"] = None  # type: ignore[assignment]

        score = _phase_score(checks, task, phase)
        feedback = _build_feedback(results, checks, score, feedback_max_chars)
        return _result_dict(checks, results, task, feedback, run_dir, keep_work, code, score=score)
    except Exception as exc:
        feedback = _truncate(f"HDL judge internal error: {type(exc).__name__}: {exc}", feedback_max_chars)
        return {
            "score": -0.1,
            "acc": 0.0,
            "hdl_feedback": feedback,
            "hdl_extract_ok": 1.0 if code.strip() else 0.0,
            "hdl_internal_error": repr(exc),
            "hdl_work_dir": str(run_dir) if keep_work else "",
        }
    finally:
        if not keep_work:
            shutil.rmtree(run_dir, ignore_errors=True)


def _result_dict(
    checks: dict[str, Any],
    results: list[CommandResult],
    task: dict[str, Any],
    feedback: str,
    run_dir: Path,
    keep_work: bool,
    code: str,
    *,
    score: float | None = None,
) -> dict[str, Any]:
    if score is None:
        score = _score_weighted(checks, task)
    command_status = {result.name: result.returncode for result in results}
    pass_all = bool(score >= 0.999)
    return {
        "score": float(score),
        "acc": 1.0 if pass_all else 0.0,
        "hdl_feedback": feedback,
        "hdl_extract_ok": 1.0 if checks.get("extract") else 0.0,
        "hdl_chisel_elab_ok": _float_or_none(checks.get("chisel_elaborate")),
        "hdl_slang_ok": _float_or_none(checks.get("slang")),
        "hdl_lint_ok": _float_or_none(checks.get("verilator_lint")),
        "hdl_sim_ok": _float_or_none(checks.get("verilator_sim")),
        "hdl_sim_mode": checks.get("verilator_sim_mode"),
        "hdl_functional_sim_ok": (
            1.0
            if checks.get("verilator_sim") and checks.get("verilator_sim_mode") == "testbench_cpp"
            else 0.0
        ),
        "hdl_auto_smoke_sim_ok": (
            1.0
            if checks.get("verilator_sim") and checks.get("verilator_sim_mode") == "auto_smoke"
            else 0.0
        ),
        "hdl_synth_ok": _float_or_none(checks.get("yosys_synth")),
        "hdl_command_status": command_status,
        "hdl_candidate_chars": len(code),
        "hdl_work_dir": str(run_dir) if keep_work else "",
    }


def _float_or_none(value: Any) -> float | None:
    if value is None:
        return None
    return 1.0 if bool(value) else 0.0
